export const APP_ROUTES_NAME = {
  homePage: "/",
  productsPage: "/shop",
  productDetail: "/shop/products/:productId",
  cartPage: "/cart",
  checkoutPage: "/checkout",
  checkoutAddress: "/checkout/address",
  checkoutPayment: "/checkout/payment/:orderId",
  checkoutSuccess: "/checkout/success/:orderId",
  // farmSystemPage: "/farm-systems",
  // bulkFeedPage: "/bulk-feed",
  // resourcesPage: "/resources",
  // aboutPage: "/about",
  // contactPage: "/contact",
  accountPage: "/account",
  orderCreationSuccessPage: "/order-creation-success/:orderId",
  // adminPanel: "/admin-panel",
  createProduct: "/admin-panel/create-product",
  // registerPage:"/register"
};
